### ISSUE TITLE
About doors

### ISSUE THREAD

**Issue by FurmaZ** [LordTiger/HeistIsland#1]
Hello is it possible to make main gate open or doors not locked?

**Comment by bdebruyn02** [comment]
Hi, im pretty sure if you get the hash code of the door you can lock it

**Comment by FurmaZ** [comment]
Thats the thing doors is locked like main gate and I cant open it lol its froz.

is it possible to make not frozen so they work?

**Comment by bdebruyn02** [comment]
I think the only way that's going to happen if you install the mlo/ymap. But if you do that you will get 3-10x longer loading times.
