### ISSUE TITLE
Stuck on loading screen and crash after loading screen

### ISSUE THREAD

**Issue by mzzg-bazsi** [LordTiger/HeistIsland#2]
Hello! Im using your script and when i connect to the server loading screen is on and than ive got a crash, or infinite loading screen. Not loading in!

![image](https://user-images.githubusercontent.com/63349432/127736099-0da9ba2c-06f3-4be0-b50d-bbd8455d0dd7.png)

**Comment by bdebruyn02** [comment]
1. Make sure you’re on server build 3324 or higher. To check this, run version in your server console.
2. Add set sv_enforceGameBuild 2189 to your server.cfg or +set sv_enforceGameBuild 2189 to your launch parameters.
